[build]
target = "x86_64-unknown-linux-gnu"
rustflags = ["--cfg=has_std"]

[target.x86_64-unknown-linux-gnu]                                                                                                                                   
linker = "/usr/bin/x86_64-linux-gnu-gcc"

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
